import React from "react";
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import Background from "./Background/background.jsx";
import Header from "./Header/header.jsx";
import Footer from "./Footer/footer.jsx";
import Login from "./Login/login.jsx";
import Sidebar from "./Sidebar/sidebar.jsx";
import StaffDashboard from "./StaffDashboard/staffDashboard.jsx";
import TableData from "./TableData/tableData.jsx";

function App() {
    const bookIssueRequests = [
        {
            id: 1,
            bookTitle: "React for Beginners",
            userName: "John Doe",
            issueDate: "2024-11-24",
            status: "Pending",
        },
        {
            id: 2,
            bookTitle: "JavaScript The Good Parts",
            userName: "Jane Smith",
            issueDate: "2024-11-23",
            status: "Pending",
        },
    ];

    const bookRequests = [
        {
            id: 1,
            bookTitle: "The Great Gatsby",
            userName: "John Doe",
            requestDate: "2024-11-20",
            status: "Pending",
        },
        {
            id: 2,
            bookTitle: "1984",
            userName: "Jane Smith",
            requestDate: "2024-11-22",
            status: "Pending",
        },
    ];

    const generateReportData = [
        {
            id: 1,
            reportName: "Monthly Sales Report",
            generatedBy: "Admin",
            date: "2024-11-01",
            status: "Completed",
        },
        {
            id: 2,
            reportName: "Yearly Revenue Report",
            generatedBy: "Manager",
            date: "2024-10-30",
            status: "Pending",
        },
    ];
    
    const generateReportColumns = [
        { header: "Report Name", key: "reportName" },
        { header: "Generated By", key: "generatedBy" },
        { header: "Date", key: "date" },
        { header: "Status", key: "status" },
    ];

    const bookIssueColumns = [
        { header: "Book Title", key: "bookTitle" },
        { header: "User Name", key: "userName" },
        { header: "Issue Date", key: "issueDate" },
        { header: "Status", key: "status" },
    ];

    const bookRequestColumns = [
        { header: "Book Title", key: "bookTitle" },
        { header: "User Name", key: "userName" },
        { header: "Request Date", key: "requestDate" },
        { header: "Status", key: "status" },
    ];

    const router = createBrowserRouter([
        {
            path: "/",
            element: (
                <>
                    <Sidebar />
                    <Header />
                    <Background />
                    <StaffDashboard />
                    <Footer />
                </>
            ),
        },
        {
            path: "/login",
            element: <Login />,
        },
        {
            path: "/book-issue-approval",
            element: (
                <>
                    <Sidebar />
                    <Header />
                    <div style={{ margin: "20px", textAlign: "center" }}>
                        <h2>Book Issue Approval</h2>
                        <TableData data={bookIssueRequests} columns={bookIssueColumns} />
                    </div>
                    <Footer />
                </>
            ),
        },
        {
            path: "/generate-report",
            element: (
                <>
                    <Sidebar />
                    <Header />
                    <div style={{ margin: "20px", textAlign: "center" }}>
                        <h2>Generate Reports</h2>
                        <TableData data={generateReportData} columns={generateReportColumns} />
                    </div>
                    <Footer />
                </>
            ),
        },
        {
            path: "/handle-book-requests",
            element: (
                <>
                    <Sidebar />
                    <Header />
                    <div style={{ margin: "20px", textAlign: "center" }}>
                        <h2>Handle Book Requests</h2>
                        <TableData data={bookRequests} columns={bookRequestColumns} />
                    </div>
                    <Footer />
                </>
            ),
        },
    ]);

    return <RouterProvider router={router} />;
}

export default App;
